palavras = {
    "apple": "maçã",
    "house": "casa",
    "car": "carro",
    "book": "livro",
    "computer": "computador",
    "phone": "telefone",
    "dog": "cachorro",
    "cat": "gato",
    "water": "água",
    "food": "comida",
    "teacher": "professor",
    "student": "estudante",
    "love": "amor",
    "friend": "amigo",
    "family": "família",
    "city": "cidade",
    "country": "país",
    "world": "mundo",
    "day": "dia",
    "night": "noite",
    "music": "música",
    "game": "jogo",
    "work": "trabalho",
    "money": "dinheiro",
    "health": "saúde",
    "happiness": "felicidade",
    "dream": "sonho",
    "light": "luz",
    "dark": "escuro",
    "road": "estrada",
    "river": "rio",
    "ocean": "oceano",
    "mountain": "montanha",
    "forest": "floresta",
    "tree": "árvore",
    "flower": "flor",
    "grass": "grama",
    "fire": "fogo",
    "wind": "vento",
    "earth": "terra",
    "sky": "céu",
    "star": "estrela",
    "moon": "lua",
    "sun": "sol",
    "rain": "chuva",
    "snow": "neve",
    "door": "porta",
    "window": "janela",
    "kitchen": "cozinha",
    "bathroom": "banheiro",
    "bedroom": "quarto",
    "living room": "sala de estar",
    "chair": "cadeira",
    "table": "mesa",
    "bed": "cama",
    "sofa": "sofá",
    "clock": "relógio",
    "shirt": "camisa",
    "pants": "calça",
    "shoes": "sapatos",
    "hat": "chapéu",
    "coat": "casaco",
    "bag": "bolsa",
    "key": "chave",
    "pen": "caneta",
    "pencil": "lápis",
    "paper": "papel",
    "notebook": "caderno",
    "map": "mapa",
    "ticket": "bilhete",
    "wallet": "carteira",
    "glasses": "óculos",
    "camera": "câmera",
    "umbrella": "guarda-chuva",
    "bottle": "garrafa",
    "cup": "copo",
    "plate": "prato",
    "spoon": "colher",
    "fork": "garfo",
    "knife": "faca",
    "fruit": "fruta",
    "vegetable": "vegetal",
    "meat": "carne",
    "fish": "peixe",
    "bread": "pão",
    "rice": "arroz",
    "egg": "ovo",
    "butter": "manteiga",
    "milk": "leite",
    "sugar": "açúcar",
    "salt": "sal",
    "pepper": "pimenta",
    "onion": "cebola",
    "garlic": "alho",
    "carrot": "cenoura",
    "potato": "batata",
    "tomato": "tomate",
    "lettuce": "alface",
    "orange": "laranja",
    "banana": "banana",
    "grape": "uva",
    "lemon": "limão",
    "strawberry": "morango",
    "chicken": "frango",
    "beef": "carne bovina",
    "pork": "carne de porco",
    "shrimp": "camarão",
    "eggplant": "berinjela",
    "broccoli": "brócolis",
    "pumpkin": "abóbora",
    "corn": "milho",
    "cucumber": "pepino",
    "spinach": "espinafre",
    "zucchini": "abobrinha",
    "train": "trem",
    "airplane": "avião",
    "ship": "navio",
    "bus": "ônibus",
    "bicycle": "bicicleta",
    "motorcycle": "moto",
    "street": "rua",
    "bridge": "ponte",
    "market": "mercado",
    "hospital": "hospital",
    "school": "escola",
    "university": "universidade",
    "park": "parque",
    "library": "biblioteca",
    "restaurant": "restaurante",
    "hotel": "hotel",
    "shop": "loja",
    "office": "escritório",
    "factory": "fábrica",
    "airport": "aeroporto",
    "bicycle": "bicicleta",
    "camera": "câmera",
    "dance": "dança",
    "egg": "ovo",
    "family": "família",
    "garden": "jardim",
    "holiday": "férias",
    "island": "ilha",
    "jungle": "selva",
    "king": "rei",
    "lake": "lago",
    "market": "mercado",
    "night": "noite",
    "ocean": "oceano",
    "paint": "pintar",
    "queen": "rainha",
    "river": "rio",
    "school": "escola",
    "train": "trem",
    "umbrella": "guarda-chuva",
    "village": "vila",
    "window": "janela",
    "xylophone": "xilofone",
    "yogurt": "iogurte",
    "zebra": "zebra",
    "actor": "ator",
    "beach": "praia",
    "cloud": "nuvem",
    "desk": "escrivaninha",
    "engine": "motor",
    "forest": "floresta",
    "guitar": "violão",
    "hotel": "hotel",
    "island": "ilha",
    "jacket": "jaqueta",
    "kitchen": "cozinha",
    "lamp": "lâmpada",
    "monkey": "macaco",
    "notebook": "caderno",
    "orange": "laranja",
    "pencil": "lápis",
    "queen": "rainha",
    "radio": "rádio",
    "shoe": "sapato",
    "table": "mesa",
    "university": "universidade",
    "volcano": "vulcão",
    "whale": "baleia",
    "yacht": "iate",
}

def menu():
    print("""\n==== Tradutor Ingles para Portugues ====
1. Adicionar uma nova palavra
2. Consultar uma palavra
3. Sair
===========================================\n""")
    
def adicionar_palavra():
    nome = input('Digite o nome da palavra em ingles: ').strip().lower()
    if nome in palavras:
        print('Palavra cadastrada!')
        return
    traducao = input('Digite a tradução para portugues: ').strip().lower()
    palavras[nome] = traducao
    print(f'Palavra {nome} adicionada com sucesso!')

def consultar_palavra():
    nome = input('Digite o nome da palavra em inglês para consultar: ').strip().lower()
    if nome in palavras:
        print(f'A tradução de "{nome}" é "{palavras[nome]}"')
    else:
        print('Palavra não encontrada!')

def main():
    while True:
        menu()
        opcao = input('Escolha uma opção: ').strip()
        if opcao == '1':
            adicionar_palavra()
        elif opcao == '2':
            consultar_palavra()
        elif opcao == '3':
            print('Saindo do sistema...')
            break
        else:
            print('Opção inválida!')

main()